"""Add Logger model

Revision ID: 6cae50a57b4c
Revises: 
Create Date: 2025-05-13 20:59:55.533049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cae50a57b4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_index(op.f('ix_games_appid'), 'games', ['appid'], unique=False)
    op.create_table('loggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loggers_id'), 'loggers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=False)
    op.create_table('alerts',
    sa.Column('alertid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['games.appid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('alertid')
    )
    op.create_index(op.f('ix_alerts_alertid'), 'alerts', ['alertid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_alertid'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_loggers_id'), table_name='loggers')
    op.drop_table('loggers')
    op.drop_index(op.f('ix_games_appid'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
